const CONSTANTS = {
  resCode: {
    HTTP_OK: 200,
    HTTP_CREATE: 201,
    HTTP_NO_CONTENT: 204,
    HTTP_BAD_REQUEST: 400,
    HTTP_UNAUTHORIZED: 401,
    HTTP_FORBIDDEN: 403,
    HTTP_NOT_FOUND: 404,
    HTTP_METHOD_NOT_ALLOWED: 405,
    HTTP_CONFLICT: 409,
    HTTP_INTERNAL_SERVER_ERROR: 500,
    HTTP_SERVICE_UNAVAILABLE: 503,
  },
  errorTypes: {
    OAUTH_EXCEPTION: 'OAuthException',
    ACCESS_DENIED_EXCEPTION: 'AccessDeniedException',
    ALREADY_AUTHENTICATED: 'AlreadyAuthenticated',
    UNAUTHORIZED_ACCESS: 'UnauthorizedAccess',
    FORBIDDEN: 'Forbidden',
    INPUT_VALIDATION: 'InputValidationException',
    ACCOUNT_ALREADY_EXIST: 'AccountAlreadyExistException',
    ACCOUNT_DOES_NOT_EXIST: 'AccountDoesNotExistException',
    ENTITY_NOT_FOUND: 'EntityNotFound',
    ACCOUNT_BLOCKED: 'AccountBlocked',
    ACCOUNT_DEACTIVATED: 'AccountDeactivated',
    CONTENT_BLOCKED: 'ContentBlocked',
    CONTENT_REMOVED: 'ContentRemoved',
    PRIVATE_CONTENT: 'PrivateContent',
    PRIVATE_ACCOUNT: 'PrivateAccount',
    DUPLICATE_REQUEST: 'DuplicateRequest',
    EMAIL_NOT_VERIFIED: 'emailNotVerified',
    MOBILE_NUMBER_NOT_VERIFIED: 'mobileNumberNotVerified',
    INTERNAL_SERVER_ERROR: 'InternalServerError',
    CATCH_ERRORS: 'Oops! something went wrong.',
    INVALID_INVITE_LINK: 'InvalidInviteLink',
    INVITE_ALREADY_USED: 'InviteAlreadyAccepted',
  },
  errorMessage: {
    UNAUTHORIZED_ACCESS: 'Not authorized to perform this action',
    UPLOAD_ALL_REQUIRED_DOCUMENTS: 'Please upload all the required documents',
    SERVER_ERROR: 'Oops! something went wrong.',
    INVALID_CREDENTIALS: 'The email and/or password entered are incorrect',
    OTP_INVALID: 'Invalid Otp',
    CONTACT_ADMIN: 'Contact admin to perform edit',
    COUNTRY_CODE: 'Please add country code',
    INCORRECT_DATA: (data: string) => `The ${data} entered is incorrect`,
    INVALID_REQUEST: 'Invalid Request',
    USER_ACCOUNT_BLOCKED: 'Your account has been blocked, Please contact admin',
    ROLE_INVALID_LOGIN: 'Account access denied',
    NO_USER: (data: string) => `User does not exists with this ${data}`,
    EXISTS_USER: (data: string) => `User exists with ${data}`,
    DOES_NOT_EXIST: (data: string) => `The ${data} does not exist`,
    ALREADY_EXIST: (data: string) => `The ${data} already exist`,
    INCORRECT_FILE_DATA: 'File contains invalid data',
    SAME_EMAIL_MOBILE_EXISTS: (data: string) =>
      `User with same ${data} already exists`,
    DATA_NOT_FOUND: 'Data not found',
    MOBILE_NUMBER_ALREADY_EXISTS:
      'User with this mobile number is already exist',
    INVALID_INVITE_LINK: 'The invite link is invalid or has expired',
    INVITE_ALREADY_USED: 'The invite link has already been accepted',
  },
  successMessage: {
    OTP_SEND: (device: string) => `An OTP has been send to your ${device}`,
    OTP_VERIFIED: () => `OTP has been verified`,
    LOG: (data: string) => `You have ${data} successfully`,
    UPDATE_SUCCESS_MESSAGE: (data: string) => `${data} updated successfully`,
    DELETE_SUCCESS_MESSAGE: (data: string) => `${data} deleted successfully`,
    REMOVED_SUCCESS_MESSAGE: (data: string) => `${data} removed successfully`,
    ADD_SUCCESS_MESSAGE: (data: string) => `${data} added successfully`,
    SAVED_SUCCESS_MESSAGE: (data: string) => `${data} saved successfully`,
    GENERATE_SUCCESS_MESSAGE: (data: string) => `${data} generate successfully`,
    CHANGED_SUCCESS_MESSAGE: (data: string) => `${data} changed successfully`,
    VERIFIED_SUCCESS_MESSAGE: (data: string) => `${data} verified successfully`,
    SEND_SUCCESS_MESSAGE: (data: string) => `${data} send successfully`,
    DETAIL_MESSAGE: (data: string) => `Fetched ${data} details successfully`,
    RESET_SUCCESS_MESSAGE: (data: string) => `reset ${data} successfully`,
  },
};
